export const bookings = [
  {
    id: 1,
    name: "Ama Kofi",
    destination: "Wa",
    depTime: "20th Jan, 2021",
    returnTime: "20th AUgust, 2021",
    reason: "i am sick of beriberi",
  },
  {
    id: 2,
    name: "Abu Ibrahim",
    destination: "Tamale",
    depTime: "11th Jul, 2022",
    returnTime: "20th Sep, 2028",
    reason: "i am sick of beriberi",
  },
  {
    id: 3,
    name: "Esi Kwaku Manu",
    destination: "Kumasi",
    depTime: "20th Jan, 2021",
    returnTime: "20th AUgust, 2021",
    reason: "i am sick of beriberi",
  },
  {
    id: 4,
    name: "Desmond Mwintegee",
    destination: "Accra",
    depTime: "20th Jan, 2021",
    returnTime: "20th AUgust, 2021",
    reason: "i am sick of beriberi",
  },
  {
    id: 5,
    name: "Joshua Stephen",
    destination: "Bolgatanga",
    depTime: "20th Jan, 2021",
    returnTime: "20th AUgust, 2021",
    reason: "i am sick of beriberi",
  },
  {
    id: 6,
    name: "Brad Traversy",
    destination: "Sunyani",
    depTime: "20th Jan, 2021",
    returnTime: "20th AUgust, 2021",
    reason: "i am sick of beriberi",
  },
  {
    id: 7,
    name: "John Smith",
    destination: "Chicago",
    depTime: "20th Jan, 2021",
    returnTime: "20th AUgust, 2021",
    reason: "i am sick of beriberi",
  },
  {
    id: 8,
    name: "Jane Steven",
    destination: "New York",
    depTime: "20th Jan, 2021",
    returnTime: "20th AUgust, 2021",
    reason: "i am sick of beriberi",
  },
  {
    id: 9,
    name: "Jack Maa",
    destination: "Nanjuang",
    depTime: "20th Jan, 2021",
    returnTime: "20th AUgust, 2021",
    reason: "i am sick of beriberi",
  },
  {
    id: 10,
    name: "Shun Damson",
    destination: "Juanghong",
    depTime: "20th Jan, 2021",
    returnTime: "20th AUgust, 2021",
    reason: "i am sick of beriberi",
  },
];
